### ISSUE TITLE
No Valid Shares with 2.5.0

### ISSUE THREAD

**Issue by Blurrrr77** [fireice-uk/xmr-stak#1952]
Please provide as much as possible information to reproduce the issue.
When running 2.4.7 I see shares while using a pool, when running 2.5.0 I have not seen a share in over an hour.  When I switch back to 2.4.7, I see the shares start up again... back to 2.5.0, no shares.

# Basic information
  - Type of the CPU. E2200
  - Type of the GPU (if you try to miner with the GPU).  (2) XFX RX570 4GB

# Compile issues
  - Which OS do you use?  Win10
  ```
  Did not compile own
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?  No
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (2671.3)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Radeon RX 570 Series
  Device Topology:                               PCI[ B#3, D#0, F#0 ]
  Max compute units:                             32
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1286Mhz
  Address bits:                                  64
  Max memory allocation:                         3422552064
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            4294967296
  Constant buffer size:                          3422552064
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          3422552064
  Max global variable size:                      3080296704
  Max global variable preferred total size:      4294967296
  Max read/write image args:                     64
  Max on device events:                          1024
  Queue on device max size:                      8388608
  Max on device queues:                          1
  Queue on device preferred size:                262144
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   00007FFCD5543FD0
  Name:                                          Ellesmere
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 2.0
  Driver version:                                2671.3
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 AMD-APP (2671.3)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash cl_amd_planar_yuv


  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Radeon RX 570 Series
  Device Topology:                               PCI[ B#4, D#0, F#0 ]
  Max compute units:                             32
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1286Mhz
  Address bits:                                  64
  Max memory allocation:                         3422552064
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            4294967296
  Constant buffer size:                          3422552064
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          3422552064
  Max global variable size:                      3080296704
  Max global variable preferred total size:      4294967296
  Max read/write image args:                     64
  Max on device events:                          1024
  Queue on device max size:                      8388608
  Max on device queues:                          1
  Queue on device preferred size:                262144
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   00007FFCD5543FD0
  Name:                                          Ellesmere
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 2.0
  Driver version:                                2671.3
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 AMD-APP (2671.3)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash cl_amd_planar_yuv

  ```

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by Blurrrr77** [comment]
Error details:
| Count | Error text                       | Last seen           |
|     2 | AMD Invalid Result GPU ID 1      | 2018-10-16 11:01:23 |
|     3 | AMD Invalid Result GPU ID 0      | 2018-10-16 11:00:59 |

Starting to see these now

**Comment by psychocrypt** [comment]
You must downgrade your driver because the shipped comoiler is briken. The
reason why your old xmr-stak works is that a precompiled code from an older
driver is used. We as developer can not solve the issue. AMD solved the
issue already in the linux ROCm driver but as I know hash currently not
fixed it in the windows driver or linux 18.3 driver.

**Comment by Blurrrr77** [comment]
I want to make sure I understand before I make a change, you are saying the block chain optimized drivers from AMD are causing this issue?  AMD has not fixed the issue yet for windows?

**Comment by psychocrypt** [comment]
It is not really the driver it is the compiler for opencl shipped with the
driver.

**Comment by Blurrrr77** [comment]
Any idea what version of the driver works with 2.5.0?  I'm not having much luck finding any driver combo that works with it.

**Comment by psychocrypt** [comment]
I read somewhere that 18.6.1 should work very well for VEGA but if 18.5.1 works for you keep it.

**Comment by cialu** [comment]
Same issue on Ubuntu 18.04 with amdgpu-pro 18.30 and xmr-stak 2.5.1.
At average, I got something like this: 
"
Good results     : 26 / 145 (17.9 %)
...
|    39 | AMD Invalid Result GPU ID 1      | 2018-10-18 10:54:04 |
|    35 | AMD Invalid Result GPU ID 2      | 2018-10-18 10:54:00 |
|    45 | AMD Invalid Result GPU ID 0      | 2018-10-18 10:53:35 |
"

**Comment by psychocrypt** [comment]
use amd rocm on linux. amd 18.3 driver are broken

**Comment by cialu** [comment]
rocm detects only one gpu. I'm trying to figure it out.

**Comment by psychocrypt** [comment]
do you use the latest rocm 1.9.X?

**Comment by cialu** [comment]
> do you use the latest rocm 1.9.X?

Yes. It detects only one GPU and 18.30 driver gives only invalid shares. I'm trying different config to see if something change.

**Comment by Spudz76** [comment]
18.1 was the last alleged good version however personally never trusted anything over 17.50, and ROCm never worked for me and had trouble using cards that weren't in the main 16x mobo slot and/or when CPU and mobo don't support PCIe Atomics.  But I believe all those old problems are better with 1.9+ it seems odd you are having problems with it.

18.20 and 18.30 will certainly never ever work right.

cast_xmr is closed source, there is no point in whether or not that app works, we can't gain anything from it other than "somehow it works".  I bet he encapsulated the older compiler to use with the newer driver cores, which is something you can do in closed source since AMD won't see that you've bundled their proprietary licensed software separate from their official driver package.  18.30 does work if you manually downgrade to the older opencl parts by hand, maybe cast-xmr just holds your hand by bringing the old OpenCL with it (grey area legally, vs AMD driver license)

**Comment by cialu** [comment]
> 18.1 was the last alleged good version however personally never trusted anything over 17.50, and ROCm never worked for me and had trouble using cards that weren't in the main 16x mobo slot and/or when CPU and mobo don't support PCIe Atomics. But I believe all those old problems are better with 1.9+ it seems odd you are having problems with it.
> 
> 18.20 and 18.30 will certainly never ever work right.
> 
> cast_xmr is closed source, there is no point in whether or not that app works, we can't gain anything from it other than "somehow it works". I bet he encapsulated the older compiler to use with the newer driver cores, which is something you can do in closed source since AMD won't see that you've bundled their proprietary licensed software separate from their official driver package. 18.30 does work if you manually downgrade to the older opencl parts by hand, maybe cast-xmr just holds your hand by bringing the old OpenCL with it (grey area legally, vs AMD driver license)

Thanks for all the info. 
I'll do some trials with ROCm and drivers, let's see what happens.

**Comment by psychocrypt** [comment]
ROCm 1.9 and AMD Driver 18.10 should work.

**Comment by BigslimVdub** [comment]
I am using 18.5.1 with no real issues with 570 gpu other than lower hash rate than on 2.4.1 by about 100 with same settings. No rejected share with stak 2.5.1.

**Comment by BKdilse** [comment]
If it help...  I'm on Windows 10, 18.5.1, 2.5.0, and hashes ok, lost around 45h/s on the RX570 (Bios Mod, and clocked).
