### ISSUE TITLE
OpenCL on nVidia hasn't worked in a while

### ISSUE THREAD

**Issue by Spudz76** [fireice-uk/xmr-stak#2112]
Previous to this compile-time crash, it would just crash when firing up the work.
Last time I had it work at all was during CN2v2 pre-fork testing phases.  Sometime after final CN2v2 and other AMD fixes, the non-AMD OpenCL broke (twice I think).
```
[2018-12-02 10:57:48] : Mining coin: cryptonight_v8
[2018-12-02 10:57:49] : Found NVIDIA platform index id = 0, name = NVIDIA Corporation
[2018-12-02 10:57:49] : Found OpenCL GPU GeForce GTX 970.
[2018-12-02 10:57:49] : NVIDIA: GPU (OpenCL) configuration stored in file 'amd.txt'
[2018-12-02 10:57:49] : Compiling code and initializing GPUs. This will take a while...
[2018-12-02 10:57:49] : Device 0 work size 8 / 128.
[2018-12-02 10:57:49] : OpenCL device 0 - Precompiled code C:\Users\tony\AppData\Local/.openclcache/a4aadd204e04b6a3524d586cce760ad0
c29a0be582e7924252eba52e05701794.openclbin not found. Compiling ...
[2018-12-02 10:57:50] : Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
<kernel>:1490:44: error: 'long long' type is not supported
        Scratchpad += (gIdx / WORKSIZE) * (MEMORY >> 4) * WORKSIZE + MEM_CHUNK * (gIdx % WORKSIZE);
                                           ^
<built-in>:28:16: note: expanded from here
#define MEMORY 2097152LLU
               ^
<kernel>:1584:29: error: 'long long' type is not supported
        for(int i = 0; i < (MEMORY >> 4); i += 8) {
                            ^
<built-in>:28:16: note: expanded from here
#define MEMORY 2097152LLU
               ^
<kernel>:1675:42: error: 'long long' type is not supported
        Scratchpad += get_group_id(0) * (MEMORY >> 4) * WORKSIZE + MEM_CHUNK * get_local_id(0);
                                         ^
<built-in>:28:16: note: expanded from here
#define MEMORY 2097152LLU
               ^
<kernel>:1905:44: error: 'long long' type is not supported
        Scratchpad += (gIdx / WORKSIZE) * (MEMORY >> 4) * WORKSIZE + MEM_CHUNK * (gIdx % WORKSIZE);
                                           ^
<built-in>:28:16: note: expanded from here
#define MEMORY 2097152LLU
               ^
<kernel>:1971:30: error: 'long long' type is not supported
        for (int i = 0; i < (MEMORY >> 7); ++i) {
                             ^
<built-in>:28:16: note: expanded from here
#define MEMORY 2097152LLU
               ^

[2018-12-02 10:57:50] : WARNING: AMD device not found
[2018-12-02 10:57:50] : WARNING: backend NVIDIA (OpenCL) disabled.
[2018-12-02 10:57:50] : ERROR: No miner backend enabled.
```

**Comment by psychocrypt** [comment]
which gpu do you use and which cuda version?

**Comment by Spudz76** [comment]
latest 417.01 driver, CUDA10 SDK
The compilation error may be related to CUDA10, I was likely getting the other explosive runtime crash on CUDA8 (which may still compile OK, but dies at worktime) I have not tried that version recently.

**Comment by Spudz76** [comment]
Found some Intel garbage in my environment which was not there to block proper location of nvidia stuff.. fixing and retesting...
```
OpenCL_INCLUDE_DIR:PATH=C:/Intel/OpenCL/sdk/include

//Path to a library.
OpenCL_LIBRARY:FILEPATH=C:/Intel/OpenCL/sdk/lib/x64/OpenCL.lib
```

**Comment by psychocrypt** [comment]
I think it is still broken I defined MEMORY in gpu.cpp as unsigned long
long but for opencl it must be unsigned long only.

**Comment by Spudz76** [comment]
I switched to building within CLion and how it does build-configurations and environments is weird.

**Comment by Spudz76** [comment]
Okay, with corrected OpenCL include/lib it still complains the same on compile phase.

**Comment by Spudz76** [comment]
that `LU` fix works, now back to the original problem which is:
```
[2018-12-02 12:10:54] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
```
no matter what I try, even ultra low intensity etc.

**Comment by psychocrypt** [comment]
fixed in #2113

**Comment by Spudz76** [comment]
Retesting both CUDA8.0 for NVS 5400M and CUDA10.0 for 970GTX with patch applied... brb

**Comment by psychocrypt** [comment]
The fix should work for all NVIDIA GPUs. Please try to clean up your opencl cache.

I tested the fix with sm_20, sm_35, sm_5X

**Comment by Spudz76** [comment]
Cleared, same.  This is SM_20 ... but laptop and Quadro (double edge case? haha)
```
  // gpu: NVS 5200M  compute units: 2
  // memory:896|1024|896 MiB (used per thread|max per alloc|total free)
  { "index" : 0,
    "intensity" : 432, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true, "interleave" : 40
  },
```
I believe it worked before, as I posted speeds during the CN2v2 design phase.
```
[2018-12-03 08:45:57] : Mining coin: cryptonight_v8
[2018-12-03 08:45:58] : Found NVIDIA platform index id = 0, name = NVIDIA Corporation
[2018-12-03 08:45:58] : Found OpenCL GPU NVS 5200M.
[2018-12-03 08:45:58] : NVIDIA: GPU (OpenCL) configuration stored in file 'amd.txt'
[2018-12-03 08:45:58] : Compiling code and initializing GPUs. This will take a while...
[2018-12-03 08:45:58] : Device 0 work size 8 / 128.
[2018-12-03 08:45:58] : OpenCL device 0 - Precompiled code C:\Users\xxxx\AppData\Local/.openclcache/1f6b7f8a10afe33f0d08cdd9051d514cc79712cacc0ad96476aa7d8185713f09.openclbin not found. Compiling ...
[2018-12-03 08:45:59] : OpenCL device 0 - Precompiled code stored in file C:\Users\xxxx\AppData\Local/.openclcache/1f6b7f8a10afe33f0d08cdd9051d514cc79712cacc0ad96476aa7d8185713f09.openclbin
[2018-12-03 08:45:59] : OpenCL device 0 - Precompiled code C:\Users\xxxx\AppData\Local/.openclcache/1efa264318b026e665031b1480993d126125a7164ca307dc2ddaa2685aab8589.openclbin not found. Compiling ...
[2018-12-03 08:46:01] : OpenCL device 0 - Precompiled code stored in file C:\Users\xxxx\AppData\Local/.openclcache/1efa264318b026e665031b1480993d126125a7164ca307dc2ddaa2685aab8589.openclbin
[2018-12-03 08:46:01] : Starting NVIDIA GPU (OpenCL) thread 0, no affinity.
[2018-12-03 08:46:01] : Fast-connecting to 0.0.0.0:4444 pool ...
[2018-12-03 08:46:01] : Pool 0.0.0.0:4444 connected. Logging in...
[2018-12-03 08:46:01] : Difficulty changed. Now: 1024.
[2018-12-03 08:46:01] : Pool logged in.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
[2018-12-03 08:46:04] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
```

Intensity 256 still not happy.

I won't use this method ever, but it should work.  CUDA generally faster.

**Comment by psychocrypt** [comment]
reduce to 128 since the fpu has nearly no compite units.

**Comment by Spudz76** [comment]
intensity 128 with strided off, same
intensity 16 also no help

**Comment by psychocrypt** [comment]
which cuda 8 version do you use? Is it the latest cuda 8?

**Comment by Spudz76** [comment]
Yes, 8.0-GA2 (`version.txt` from installed SDK folder):
```
CUDA Version 8.0.61
CUDA Patch Version 8.0.61.2
```
Rebased again on latest `dev` @ `6765ef4e3c24d8b6c0b78e12e40ef36468e30d38` and same

Agree it could be something with my environment or compiler, although nothing should have changed with the v14.0 toolkit and compiler.

CUDA10 works great even with 14.16 compiler I just updated and tried it out.  Half expected it to complain without 14.15 based on older version headers having tight version slotting.

**Comment by psychocrypt** [comment]
ahh you are using windows. I used always linux ;-)
I have no windows system with auch an old gpu :-(

**Comment by kneespan** [comment]
Any solution here? I have the same effect since 0.2.10. Thanks

**Comment by psychocrypt** [comment]
wich currency? please also provide your amd.txt and nvidia.txt

**Comment by Spudz76** [comment]
This works fine with newer versions but it's slower than CUDA directly.
One of the AMD driver crash fixes fixed whatever this OpenCL didn't like.

**Comment by kneespan** [comment]
"currency" : "monero",
Win 10 64bit

It's a GTX 570 - since it doesn't work with CUDA I used OpenCL for it on 2.5.0 and it worked. Since 2.10.0 I got this error. Here are my parameters:

xmr-stak.exe --noNVIDIA --openCLVendor NVIDIA --noCPU

amd.txt:
"gpu_threads_conf" : [
  // gpu: GeForce GTX 570  compute units: 15
  // memory:1152|1280|1152 MiB (used per thread|max per alloc|total free)
  { "index" : 0,
    "intensity" : 480, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true, "interleave" : 40
  },

],

nvidia.txt is should be irrelevant since starting with -noNVIDIA

I allready tried deleting the OpenCL Cache, unfortunately no luck.

Any ideas and suggestions are very appreciated. Thank you.

**Comment by psychocrypt** [comment]
could you set the intensity to 384 and test it again.

**Comment by Spudz76** [comment]
I have tested nv-OpenCL on my CUDA8 also and it still streams the out of resources errors.
CUDA 10.1 on GTX970 works fine.
I had assumed the 10.1 suddenly started working again that both had...

**Comment by kneespan** [comment]
> 
> could you set the intensity to 384 and test it again.

still no luck - here the complete output:
C:\Users\kneesock\Downloads\xmr-stak-win64>xmr-stak.exe --noNVIDIA --openCLVendor NVIDIA --noCPU
[2019-03-10 11:30:15] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
-------------------------------------------------------------------
xmr-stak 2.10.0 56d2770ff

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2019-03-10 11:30:15] : Mining coin: cryptonight_r
[2019-03-10 11:30:15] : Compiling code and initializing GPUs. This will take a while...
[2019-03-10 11:30:16] : Device 0 work size 8 / 128.
[2019-03-10 11:30:16] : OpenCL device 0 - Load precompiled code from file C:\Users\kneesock\AppData\Local/.openclcache/4e08d8e71f1ea15035527c6f049520db71ae893a83d49f8b659642c5121eb7d7.openclbin
[2019-03-10 11:30:16] : OpenCL device 0 - Load precompiled code from file C:\Users\kneesock\AppData\Local/.openclcache/8a104629e5b0691ee7995256cd59bb9a6b2e91144f191a035e354bb9063a9b1c.openclbin
[2019-03-10 11:30:16] : Starting NVIDIA GPU (OpenCL) thread 0, no affinity.
[2019-03-10 11:30:16] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2019-03-10 11:30:16] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2019-03-10 11:30:16] : Difficulty changed. Now: 25000.
[2019-03-10 11:30:16] : Pool logged in.
[2019-03-10 11:30:16] : Error UNKNOWN_ERROR when calling clBuildProgram.
Build log:
ptxas application ptx input, line 16; error   : Feature 'Unsized Array Parameter' requires .target sm_30 or higher
ptxas application ptx input, line 16; error   : Feature 'Unsized Array Parameter' not supported with '-new-sm3x-opt=false'
ptxas application ptx input, line 403; error   : Call has wrong number of parameters
ptxas application ptx input, line 403; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 403; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 430; error   : Call has wrong number of parameters
ptxas application ptx input, line 430; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 430; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 456; error   : Call has wrong number of parameters
ptxas application ptx input, line 456; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 456; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 482; error   : Call has wrong number of parameters
ptxas application ptx input, line 482; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 482; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 509; error   : Call has wrong number of parameters
ptxas application ptx input, line 509; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 509; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 536; error   : Call has wrong number of parameters
ptxas application ptx input, line 536; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 536; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 562; error   : Call has wrong number of parameters
ptxas application ptx input, line 562; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 562; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 588; error   : Call has wrong number of parameters
ptxas application ptx input, line 588; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 588; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 614; error   : Call has wrong number of parameters
ptxas application ptx input, line 614; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 614; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 641; error   : Call has wrong number of parameters
ptxas application ptx input, line 641; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 641; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 667; error   : Call has wrong number of parameters
ptxas application ptx input, line 667; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 667; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 693; error   : Call has wrong number of parameters
ptxas application ptx input, line 693; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 693; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 720; error   : Call has wrong number of parameters
ptxas application ptx input, line 720; error   : Type of argument does not m
[2019-03-10 11:30:17] : Error UNKNOWN_ERROR when calling clBuildProgram.
Build log:
ptxas application ptx input, line 16; error   : Feature 'Unsized Array Parameter' requires .target sm_30 or higher
ptxas application ptx input, line 16; error   : Feature 'Unsized Array Parameter' not supported with '-new-sm3x-opt=false'
ptxas application ptx input, line 403; error   : Call has wrong number of parameters
ptxas application ptx input, line 403; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 403; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 430; error   : Call has wrong number of parameters
ptxas application ptx input, line 430; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 430; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 456; error   : Call has wrong number of parameters
ptxas application ptx input, line 456; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 456; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 482; error   : Call has wrong number of parameters
ptxas application ptx input, line 482; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 482; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 509; error   : Call has wrong number of parameters
ptxas application ptx input, line 509; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 509; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 536; error   : Call has wrong number of parameters
ptxas application ptx input, line 536; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 536; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 562; error   : Call has wrong number of parameters
ptxas application ptx input, line 562; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 562; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 588; error   : Call has wrong number of parameters
ptxas application ptx input, line 588; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 588; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 614; error   : Call has wrong number of parameters
ptxas application ptx input, line 614; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 614; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 641; error   : Call has wrong number of parameters
ptxas application ptx input, line 641; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 641; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 667; error   : Call has wrong number of parameters
ptxas application ptx input, line 667; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 667; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 693; error   : Call has wrong number of parameters
ptxas application ptx input, line 693; error   : Type of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 693; error   : Alignment of argument does not match formal parameter '%VAParam'
ptxas application ptx input, line 720; error   : Call has wrong number of parameters
ptxas application ptx input, line 720; error   : Type of argument does not m
[2019-03-10 11:30:20] : Error UNKNOWN_ERROR when calling clBuildProgram.
[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
Build log:
[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
p[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
x[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
a[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
s[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
a[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
p[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
pl[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
c[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
a[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
o[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
n[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
p[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
x[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
n[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
p[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
u[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
, [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
l[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
ne 16[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
;[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
o[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 :[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
F[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
eatu[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
'[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
U[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
nsi[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
z[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
ed[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 A[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
ay[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 Pa[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
a[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
m[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
er[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
'[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
q[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
u[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
s[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
.t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
a[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
g[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 sm_30 or high[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
er[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.

[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
p[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
xas application pt[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
x[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
n[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
p[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
u[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
,[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
l[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
n[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
1[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
6[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
;[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
o[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
:[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
Fe[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
a[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
t[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
u[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
r[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
e[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
 [2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
'[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
U[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
n[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
s[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
i[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
z[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.
ed[2019-03-10 11:30:20] : Error CL_OUT_OF_RESOURCES when calling clEnqueueReadBuffer to fetch results.

**Comment by Spudz76** [comment]
Similar, I however do not get the compile errors, just the others
