### ISSUE TITLE
Dev pool socket error - mining on user pool...

### ISSUE THREAD

**Issue by ITwrx** [fireice-uk/xmr-stak#2329]
Please provide as much as possible information to reproduce the issue.

# Basic information
  
  - Type of the GPU (if you try to miner with the GPU).
rx570, rx470, rx 480 (several different ones on different machines)

  - Which OS do you use?
  arch linux and ubuntu 18.04  

# Issue with the execution
  - Do you compiled the miner by our own?
running the linux precompiled binaries right now.
  ```

  run `./xmr-stak --version-long` and add the output here
  ```
Version: xmr-stak/2.10.0/56d2770/master/lin/amd-cpu/20

# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

the dev pool is having connection issues (i'm using tls, of course) and it's interupting my mining. The log says "mining on user pool" but it's not mining...

**Comment by psychocrypt** [comment]
which currency do you mine. Which version do you use (first line after the
start)

**Comment by ITwrx** [comment]
monero. i posted the version above, but it's xmr-stak 2.10.0 56d2770. this only started with v2.10. v2.8 worked fine, but i may have been mining loki the whole time with that version. v2.7 was definitely used with monero and didn't have this problem.

**Comment by ITwrx** [comment]
this is still happening with 2.10.1

**Comment by psychocrypt** [comment]
this should not be an issue. ig you can not connect to the dev pool you
will stay with the user pool all the time

**Comment by ITwrx** [comment]
it's crashing opencl but it keeps happening during the devpool switch/attempted switch.

also, i wonder why this dev pool related issue didn't happen when i mined loki but does happen when i mine monero?

**Comment by psychocrypt** [comment]
Ok if you miner monero and it crashed the reason is something else. There
is a memory leak in the codebase. I fixed it today and will provide today
or tomorrow new binaries.

**Comment by ITwrx** [comment]
i saw that something was using lots of system ram but wanted to confirm it was xmr-stak before reporting. thanks for your work. i'll watch for the new release. i'll close this if it fixes the problem.

**Comment by ITwrx** [comment]
2.10.2 fixed it. thanks

**Comment by ITwrx** [comment]
this is still happening it's just taking longer. i checked ram usage on one of the machines and it was normal/low. all machines show multiple "connecting to dev pool" in log output when they stop mining. the issue is not crashing opencl anymore since 2.10.2, but it stops mining and xmr-stak has to be restarted.

**Comment by Sablebeast** [comment]
Hey was that problem corrected?

**Comment by ITwrx** [comment]
i'm going to close this as i think this is probably still due to a memory leak but it takes a day or two to hang up. not sure why it seems to coincide with the dev pool switch.

**Comment by ITwrx** [comment]
miners still stop mining with 2.10.4. the screen output seems strange to me. mem usage seems normal or has been freed by the time i check it.

[2019-04-24 05:40:16] : OpenCL Interleave 4|0: 17/3028.13 ms - 45.0
[2019-04-24 05:40:32] : OpenCL Interleave 1|1: 15/3273.46 ms - 45.0
[2019-04-24 05:40:34] : OpenCL Interleave 4|0: 106/3028.18 ms - 45.0
[2019-04-24 05:56:32] : SOCKET ERROR - [pool.supportxmr.com:9000] RECEIVE error: socket closed
[2019-04-24 05:56:32] : All pools are dead. Idling...
[2019-04-24 05:57:01] : Fast-connecting to pool.supportxmr.com:9000 pool ...
[2019-04-24 05:57:01] : TLS fingerprint [pool.supportxmr.com:9000] SHA256:aRAiaDMjcecm8rXV6cXX+ORoi9Cl2RcSQ/N/oDHZQwI=
[2019-04-24 05:57:01] : Pool pool.supportxmr.com:9000 connected. Logging in...
[2019-04-24 06:04:15] : Fast-connecting to dev pool ...
[2019-04-24 06:04:15] : Dev pool connected. Logging in...
[2019-04-24 07:44:14] : Fast-connecting to dev pool ...
[2019-04-24 07:44:15] : Dev pool connected. Logging in...
[2019-04-24 09:24:13] : Fast-connecting to dev pool ...
[2019-04-24 09:24:14] : Dev pool connected. Logging in...
[2019-04-24 11:04:14] : Fast-connecting to dev pool ...
[2019-04-24 11:04:15] : Dev pool connected. Logging in...
[2019-04-24 11:50:13] : SOCKET ERROR - [pool.supportxmr.com:9000] RECEIVE error: socket closed
[2019-04-24 11:50:13] : All pools are dead. Idling...
[2019-04-24 11:50:43] : Fast-connecting to pool.supportxmr.com:9000 pool ...
[2019-04-24 11:50:43] : TLS fingerprint [pool.supportxmr.com:9000] SHA256:JEAVQ8cbvws+0HJLLnTN6ioBmjrJrbE8vViyZf95fXw=
[2019-04-24 11:50:43] : Pool pool.supportxmr.com:9000 connected. Logging in...

feel free to let me know if i need to open a new issue.

**Comment by ITwrx** [comment]
i now notice that when the miner hangs up, cpu usage is 100% when screen output shows 
```
Fast-connecting to dev pool ...
Dev pool connected. Logging in...
```
i'm running xmr-stak with 

> --noCPU

**Comment by psychocrypt** [comment]
if the dev pool is not available than the miner try to connect again and
agin to reach the pool but the miner will stay mining on the user pool.
I will try if I can see any strange behaviour

**Comment by ITwrx** [comment]
you've told me that before, but this dev pool stuff has been going on for many, many releases and it doesn't keep mining on the user pool, at least after a certain point. it either has a memory leak, runs the cpu up, or crashes opencl. Several cards may be required to cause the error. There may be a combination of issues that are causing things to screw up, but it constantly manifests with the dev pool connection issue. 

also, i wonder why the dev pool is constantly unavailable? i read something about an tls emulator or something? is the dev pool not using an actual GNU+Linux server with proper tls or something? 

IMHO, these types of ongoing issues are way more important than redoing the config/setup stuff or making guis, or even additional coins. 

thanks for looking into it.

**Comment by psychocrypt** [comment]
I check the dev pool tls port and the pool is online. IMO the issue is
somewhere on your side. Could it be that your firewall is blocking the
connection.

**Comment by psychocrypt** [comment]
please run:  'telnet donate.xmr-stak.net 8822' on the terminal and post the
output.

psychocrypt <psychocrypthpc@gmail.com> schrieb am Do., 25. Apr. 2019, 19:58:

> I check the dev pool tls port and the pool is online. IMO the issue is
> somewhere on your side. Could it be that your firewall is blocking the
> connection.
>

**Comment by ITwrx** [comment]
it's online right now (and most of the time) and i'm mining just fine. If it were my firewall the issue wouldn't be random, it would be all the time. This has been happening since i started using xmr-stak. At least since 2.0.0. I've reported and closed reports and commented in other similar reports before with various memory leaks, opencl, card difficulty, etc issues taking the blame. 

the problem (as far as i can tell) is the dev pool seems to have some kind of intermittent problem which the miner doesn't handle very well. Maybe it's running windows and is doing god knows what? even if my internet connection is dropping out without me knowing, the miner needs to be able to handle that without crashing opencl, running up the cpu to 100% (until i notice it and kill it) and/or never start mining to the user pool again. From what i've seen the miner does handle my internet outages just fine. It's only when it's trying to connect to the dev pool that it sometimes acts stupid. Unless that's a coincidence. 

maybe you would have to simulate a down dev pool with an actual miner (with several cards) to be able to verify that it doesn't always handle it like it was designed to. It doesn't just calmly keep mining on my user pool until the dev pool comes back. something seems to go wrong during that process, though the log/screen output doesn't show exactly what's going on, or i would be more sure and able to tell you exactly what was going wrong. The outages often seem to happen on more than one machine (but not all of them) around the same time and it's happening on miners with different cards, card count and distros. All AMD cards on GNU+Linux though.

output of telnet is 

```
Trying 217.23.9.20...
Connected to donate.xmr-stak.net.
Escape character is '^]'.

```
thanks

**Comment by ITwrx** [comment]
could difficulty being too high cause this in some way?

**Comment by ITwrx** [comment]
2.10.4 seems to be worse than 2.10.3 in regards to this issue. i have 3 miners offline right now.

```
[2019-04-26 09:31:47] : OpenCL Interleave 2|0: 22/2808.10 ms - 45.0
[2019-04-26 09:31:47] : OpenCL Interleave 3|0: 41/2882.95 ms - 45.0
[2019-04-26 09:36:10] : Fast-connecting to dev pool ...
[2019-04-26 09:36:10] : Dev pool connected. Logging in...
[2019-04-26 11:16:09] : Fast-connecting to dev pool ...
[2019-04-26 11:16:10] : Dev pool connected. Logging in...
```
from what i can tell from the log, once it tries to connect to the dev pool it never goes back to mining on the user pool. it might be helpful if the output/log showed whether it was mining on the dev pool or not. in the gap shown between 9:36 and 11:16 the user pool hash graph confirms that this miner never went back to mining on the user pool. i don't want to compile and remove the donation, but i may have to if this doesn't get fixed soon, as this costs me a lot of time. 
also, the cpu of the miner is pegged at 100%. I'm guessing since 9:31 am!

**Comment by ITwrx** [comment]
maybe the user pool has a finicky connection and xmr-stak doesn't try hard enough? i'm using pool.supportxmr.com:9000 on the miners in question right now.

**Comment by ITwrx** [comment]
hmm, one of my miners has memory leak with xmr-stak 2.10.4.

**Comment by ITwrx** [comment]
still a mem leak with 2.10.4.

**Comment by ITwrx** [comment]
something changed over the last few days. no hangs/crashes. i only adjusted the difficulty down on one rig.
