### ISSUE TITLE
 In Linux/Ubuntu "MEMORY ALLOC FAILED: mmap failed" resolved

### ISSUE THREAD

**Issue by jjaone** [fireice-uk/xmr-stak#878]
# Basic information
  - Type of the CPU; AMD Athlon II X4 640
  - Type of the GPU (if you try to miner with the GPU): just CPU mining

# Compile environment:
  - Which OS do you use? Ubuntu 16.04/Linux
 
# Building/compiling: ok
  - Do you compiled the miner by our own? yes
  ```
  run `./xmr-stak --version-long` and add the output here
  ```
`xmr-stak/2.2.0/2ae7260/master/lin/cpu/aeon-monero/20`

# Stability (not an issue)
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

# Linux/Ubuntu 16.04 mmap error
Running bin/xmr-stak causes  `MEMORY ALLOC FAILED: mmap failed` error for each core

# Resolving the issue
Just need to run:
`sudo sysctl -w vm.nr_hugepages=128`

and restart and no mmap errors are displayd.

Also, I didn't need the set the ulimits cause they were already 'unlimited'.

**Comment by JerichoJones** [comment]
Please fill out the template properly.

# Issue Compiling STAK

```
 - Which OS do you use?
 
 - What software are you using to compile? Include versions (this can be very important).
 
 - Add **all** commands you used and the **full** compile output here
 
 - Run `cmake -LA .` in the build folder and add the output here
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.

---

**Comment by jjaone** [comment]
The build and compile details are completely irrelevant to the issue, which I posted as a resolution to the mmap error when running  xmr_stak in Linux if the hugepages is not setup properly. 

I posted that to be. helpful tweak to others that might wonder how to resolve it, and you are nitpicking about the template usage. If you don't like my contribution just close and delete it, if you find it useful let it be as it is.

**Comment by JerichoJones** [comment]
@jjaone My apologies... moving a bit too fast through the issues.

Thanks for the post!

**Comment by VirtuBox** [comment]
Hello, 

it may be a good idea to replace the command : 
```
sudo sysctl -w vm.nr_hugepages=128
```
by 
```
echo "vm.nr_hugepages=128" >> /etc/sysctl.conf
sysctl -p
```
Otherwise, the sysctl configuration with be reset after a reboot.

**Comment by Extarys** [comment]
Hmm I have `vm.nr_hugepages=128` set in my sysctl.colnf file but I still got the error, even after a reboot.
Any idea what I can do?

**Comment by VirtuBox** [comment]
What is the output of the command : `sudo sysctl -w vm.nr_hugepages=128` ?

**Comment by Extarys** [comment]
128 - But I just tried 256 and it works.. :P

**Comment by MoonGem** [comment]
run as sudo

**Comment by Levalicious** [comment]
@MoonGem Makes no difference.

**Comment by Kogam22** [comment]
Any solution ?

**Comment by Spudz76** [comment]
Solution to what, [reading the docs](https://github.com/fireice-uk/xmr-stak/blob/master/doc/FAQ.md#error-memory-alloc-failed-mmap-failed)?  Knowing how to set sysctls and ulimits?  Being root?

Also try "no_mlck" mode instead of default "warn" as that also gets rid of locking errors (because memory doesn't actually have to be locked, in Linux)

**Comment by Spudz76** [comment]
Also, do not put it directly in `/etc/sysctl.conf` as that is literally wrong even though it works, use `/etc/sysctl.d/10-hugepages.conf` as user or package mods must add customizations there on all Linux since decades.

**Comment by jjaone** [comment]
@Spudz76 In local single user Linux systems using. /etc/sysctl.conf is just fine.

**Comment by Spudz76** [comment]
Don't argue about best practices.

Sure you can drive your personal car off a cliff too, and nobody would care, but it is clearly not best practice.  Better to not let people know that doing it wrong is even an option.

**Comment by nuke-web3** [comment]
Found this thread and it looks like for anyone else the best practice to solve this is to the run the `randomx_booster.sh` script pre-run every time. This will be located in you `xmr-stak/build/bin` folder.

Also to avoid this you can add huge pages support globally after running that script:

```
echo 'vm.nr_hugepages=1280' >> /etc/sysctl.conf
sudo sysctl -p
```

**Comment by m00nwtchr** [comment]
I'm just gonna leave this link here... https://wiki.archlinux.org/index.php/Sysctl#Configuration


Note: From version 207 and 21x, systemd only applies settings from /etc/sysctl.d/\*.conf and /usr/lib/sysctl.d/*.conf. If you had customized /etc/sysctl.conf, you need to rename it as /etc/sysctl.d/99-sysctl.conf. If you had e.g. /etc/sysctl.d/foo, you need to rename it to /etc/sysctl.d/foo.conf.

/etc/sysctl.conf has been deprecated for 8 years now...

**Comment by jjaone** [comment]
No, it hasn't been deprecated for 8 years.

**Comment by jjaone** [comment]
@lmarianski No it hasn't been deprecated for 8 years. Also, your comment and link is irrelevant for the issue, which has been already resolved here.

**Comment by jjaone** [comment]
@NukeManDan Issue has already been resolved, closing the ticket.

**Comment by nuke-web3** [comment]
I still need yo use this optimization script to maximize my hash rate. So @jjaone what must I do to not need this do you think? Might be I just need to update? My version is a few months old now iirc

**Comment by jjaone** [comment]
@NukeManDan Open a new ticket for that question or issue ;)

**Comment by tkalfaoglu** [comment]
Sorry to bring this back up, but the huge pages issue is back despite the sysctl..
This is CentOS 8 with all updates.  
4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

my startup script (the vm.nr_hugepages=128 exists in /etc/sysctl.conf as well) :

sysctl -w vm.nr_hugepages=128
/usr/bin/nice -n 19 ./xmr-stak-rx

result:
```
vm.nr_hugepages = 128
[2021-07-22 08:34:07] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2021-07-22 08:34:07] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2021-07-22 08:34:07] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2021-07-22 08:34:07] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2021-07-22 08:34:07] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2021-07-22 08:34:07] : start self test for 'randomx' (can be disabled with the command line option '--noTest')
```

**Comment by tkalfaoglu** [comment]
Update: I tried it again a few times and it eventually did not give the error and started working (!)
